# version: 2.1
#   orbs:
#     welcome: circleci/welcome-orb@0.3.1
#   workflows:
#     welcome:
#       jobs:
#         - welcome/run
    
  version: 2.1
  jobs:
    build:
      docker: 
        - image: circleci/node:10 # the primary container, where your job's commands are run
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
